### ISSUE TITLE
Generated ical not importing events in outlook

### ISSUE THREAD

**Issue by KevinHoughton** [markuspoerschke/iCal#88]
Reference to this issue on stackoverflow: http://stackoverflow.com/questions/43249331/outlook-web-app-is-not-importing-events-from-my-generated-icalendar

When a student wants to subscribe to his or her calender, we generate an URL which can be filled into Google Calender and Outlook. Except the last mentioned `outlook` it isn't importing any events.

Example of how our generated ICS looks like. This contains 1 event with the description of 'test'.

    BEGIN:VCALENDAR 
    VERSION:2.0 
    PRODID:www.onderwijsonline.nl 
    X-PUBLISHED-TTL:PT15M 
    BEGIN:VEVENT 
    UID:58e5f21fc2551 
    DTSTART;TZID=Europe/Amsterdam:20170406T090000 
    SEQUENCE:0 
    TRANSP:OPAQUE DTEND;TZID=Europe/Amsterdam:20170406T140000 URL:http://oo.dev/calendar/event/420 
    SUMMARY:Test 
    CLASS:PUBLIC 
    DTSTAMP:20170406T094535Z 
    END:VEVENT 
    END:VCALENDAR

The script that calls the package to generate this:

    public function getIcal($token = null)
        {
            $user = $this->userRepository->getByToken($token);
    
            $vCalendar = new \Eluceo\iCal\Component\Calendar('www.onderwijsonline.nl');
            $vCalendar->setPublishedTTL('PT15M');
    
            if (!is_null($user)) {
    
                /**
                 * Calendar events
                 */
                $events = $this->calendarRepository->getEventsForUser($user->id, Carbon::now()->subWeeks(2), Carbon::now()->addWeeks(6));
                foreach ($events as $event) {
    
                    $vEvent = new \Eluceo\iCal\Component\Event();
    
                    $vEvent
                        ->setUseTimezone(true)
                        ->setUseUtc(false)
                        ->setDtStart(Carbon::parse($event['start']))
                        ->setDtEnd(Carbon::parse($event['end']))
                        ->setNoTime(($event['allDay'] == 1 ? true : false))
                        ->setUrl($event['href'])
                        ->setDescription($event['description'])
                        ->setSummary($event['title']);
    
                    $vCalendar->addComponent($vEvent);
                }
    
                /**
                 * Project events
                 */
                $events = $this->calendarRepository->getEventsForProjects($user->id, null, null);
    
                foreach ($events as $event) {
                    $vEvent = new \Eluceo\iCal\Component\Event();
    
                    $vEvent
                        ->setUseTimezone(true)
                        ->setUseUtc(false)
                        ->setDtStart(Carbon::parse($event['start']))
                        ->setDtEnd(Carbon::parse($event['end']))
                        ->setNoTime(($event['allDay'] == 1 ? true : false))
                        ->setUrl($event['href'])
                        ->setSummary($event['title']);
    
                    $vCalendar->addComponent($vEvent);
                }
    
                /**
                 * Timetable events
                 */
                $events = $this->calendarRepository->getEventsForTimetables($user->id, Carbon::now()->subWeeks(2), Carbon::now()->addWeeks(6));
                foreach ($events as $event) {
                    $vEvent = new \Eluceo\iCal\Component\Event();
    
                    $vEvent
                        ->setUseTimezone(true)
                        ->setUseUtc(false)
                        ->setDtStart(Carbon::parse($event['start']))
                        ->setDtEnd(Carbon::parse($event['end']))
                        ->setNoTime(($event['allDay'] == 1 ? true : false))
                        ->setSummary($event['title']);
    
                    $vCalendar->addComponent($vEvent);
                }
            }
    
            header('Content-Type: text/calendar; charset=utf-8');
            header('Content-Disposition: inline; filename=onderwijsonline.ics');
    
            return $vCalendar->render();
        }

As I've mentioned above, this exact setup works fine for Google Calendar, but is not for outlook.

**Comment by KevinHoughton** [comment]
Test case: https://beta.onderwijsonline.nl/calendar/ical/eyJpdiI6ImZqU0hPZlwvcnIrMmNubWRadE01N1NnPT0iLCJ2YWx1ZSI6IjB2QzhabUJVQ3VreDNFbGtyWHhNaGc9PSIsIm1hYyI6ImU5YmMzNGZmNzY3NDMwNjk3OTk4ZTA2ZTVlOWJmYzYxYmMxOGY5ZjU2MDFmYmZlOTVkMGE4OTM3ZGM4MjEwYzQifQ==

**Comment by markuspoerschke** [comment]
There is no `DTSTART` within the generated ical file. Which version do you use? Maybe this is fixed for all day events in #83 ?

**Comment by KevinHoughton** [comment]
Version that is being used is: 0.10.*, I just updated to 0.11.* on the servers, which is on the url I mentioned above. But still no luck on Outlook.

**Comment by KevinHoughton** [comment]
Could there be an issue in the protocol that is being used? In every example outlook uses `webcal://`, not `https://` or `http://`.

**Comment by Fh-jashmore** [comment]
You said this is being output to a url? Are there any other headers?

**Comment by KevinHoughton** [comment]
@Fh-jashmore all headers are set as said in the documentation.

```
header('Content-Type: text/calendar; charset=utf-8');
header('Content-Disposition: inline; filename=onderwijsonline.ics');
```

**Comment by KevinHoughton** [comment]
What's the progress for this issue? @markuspoerschke

**Comment by markuspoerschke** [comment]
@KevinHoughton I just tested the URL above and the events are working in Apple’s calendar. There I can see the events. Sadly I have not access to Outlook where I could test your file. To mee it looks good. I will attach a screenshot how it looks like to me.

<img width="1270" alt="ical" src="https://cloud.githubusercontent.com/assets/1222377/25003631/ba84d9c4-2050-11e7-943a-79fb2bfe6396.png">

**Comment by markuspoerschke** [comment]
Did you try to simplify the calendar file for outlook? Mayb you can first start with a simple event with title and time only. And later on you could enable timezone etc. Maybe that could be a possibility to dissect and finally find the problem.

**Comment by Fh-jashmore** [comment]
I spent around 8 hours trying to duplicate outlook files that were working with outlook. I couldn't figure it out. And I tried simple stuff. I'm not 100% sure its the calendar file.

**Comment by KevinHoughton** [comment]
Maybe this helps? 

https://icalendar.org/validator.html?url=https://beta.onderwijsonline.nl/calendar/ical/eyJpdiI6InIzZ3lXbjcwTTBRU3RpNE91aDRVdGc9PSIsInZhbHVlIjoiSHo4OUcxbGZjUVJxNHlzNndnK1NKQT09IiwibWFjIjoiZDAwY2JlMjM1NDI1OTk0OWVmYjViNzQzNmJkM2EwM2VkMTY1M2QwNmEyZThiNzI0MTJhNmM4YjFlMmZlY2UxNSJ9

**Comment by KevinHoughton** [comment]
@markuspoerschke I've fixed it. I've added the extra code from example 5 and made my events using datetime.

```
 public function getIcal($token = null)
    {
        $user = $this->userRepository->getByToken($token);

        $vCalendar = new Calendar('www.onderwijsonline.nl');
        $vCalendar->setPublishedTTL('PT15M');

        // set default timezone (PHP 5.4)
        $tz  = 'Europe/Amsterdam';
        $dtz = new \DateTimeZone($tz);
        date_default_timezone_set($tz);

        // 2. Create timezone rule object for Daylight Saving Time
        $vTimezoneRuleDst = new TimezoneRule(TimezoneRule::TYPE_DAYLIGHT);
        $vTimezoneRuleDst->setTzName('CEST');
        $vTimezoneRuleDst->setDtStart(new \DateTime('1981-03-29 02:00:00', $dtz));
        $vTimezoneRuleDst->setTzOffsetFrom('+0100');
        $vTimezoneRuleDst->setTzOffsetTo('+0200');
        $dstRecurrenceRule = new RecurrenceRule();
        $dstRecurrenceRule->setFreq(RecurrenceRule::FREQ_YEARLY);
        $dstRecurrenceRule->setByMonth(3);
        $dstRecurrenceRule->setByDay('-1SU');
        $vTimezoneRuleDst->setRecurrenceRule($dstRecurrenceRule);

        // 3. Create timezone rule object for Standard Time
        $vTimezoneRuleStd = new TimezoneRule(TimezoneRule::TYPE_STANDARD);
        $vTimezoneRuleStd->setTzName('CET');
        $vTimezoneRuleStd->setDtStart(new \DateTime('1996-10-27 03:00:00', $dtz));
        $vTimezoneRuleStd->setTzOffsetFrom('+0200');
        $vTimezoneRuleStd->setTzOffsetTo('+0100');
        $stdRecurrenceRule = new RecurrenceRule();
        $stdRecurrenceRule->setFreq(RecurrenceRule::FREQ_YEARLY);
        $stdRecurrenceRule->setByMonth(10);
        $stdRecurrenceRule->setByDay('-1SU');
        $vTimezoneRuleStd->setRecurrenceRule($stdRecurrenceRule);

        // 4. Create timezone definition and add rules
        $vTimezone = new Timezone($tz);
        $vTimezone->addComponent($vTimezoneRuleDst);
        $vTimezone->addComponent($vTimezoneRuleStd);
        $vCalendar->setTimezone($vTimezone);

        if (!is_null($user)) {

            /**
             * Calendar events
             */
            $events = $this->calendarRepository->getEventsForUser($user->id, Carbon::now()->subWeeks(2), Carbon::now()->addWeeks(6));
            foreach ($events as $event) {

                $vEvent = new Event();

                $vEvent
                    ->setUseTimezone(true)
                    ->setUseUtc(false)
                    ->setDtStart(new \DateTime(Carbon::parse($event['start']), $dtz))
                    ->setDtEnd(new \DateTime(Carbon::parse($event['end'])))
                    ->setNoTime(($event['allDay'] == 1 ? true : false))
                    ->setUrl($event['href'])
                    ->setDescription($event['description'])
                    ->setSummary($event['title']);

                $vCalendar->addComponent($vEvent);
            }

            /**
             * Project events
             */
            $events = $this->calendarRepository->getEventsForProjects($user->id, null, null);

            foreach ($events as $event) {
                $vEvent = new Event();

                $vEvent
                    ->setUseTimezone(true)
                    ->setUseUtc(false)
                    ->setDtStart(new \DateTime(Carbon::parse($event['start']), $dtz))
                    ->setDtEnd(new \DateTime(Carbon::parse($event['end'])))
                    ->setNoTime(($event['allDay'] == 1 ? true : false))
                    ->setUrl($event['href'])
                    ->setSummary($event['title']);

                $vCalendar->addComponent($vEvent);
            }

            /**
             * Timetable events
             */
            $events = $this->calendarRepository->getEventsForTimetables($user->id, Carbon::now()->startOfWeek(), Carbon::now()->startOfWeek()->addWeeks(4));
            foreach ($events as $event) {
                $vEvent = new Event();

                $vEvent
                    ->setUseTimezone(true)
                    ->setUseUtc(false)
                    ->setDtStart(new \DateTime(Carbon::parse($event['start']), $dtz))
                    ->setDtEnd(new \DateTime(Carbon::parse($event['end'])))
                    ->setNoTime(($event['allDay'] == 1 ? true : false))
                    ->setSummary($event['title']);

                $vCalendar->addComponent($vEvent);
            }
        }

        header('Content-Type: text/calendar; charset=utf-8');
        header('Content-Disposition: inline; filename=onderwijsonline.ics');

        return $vCalendar->render();
    }
```
